name: timer
pack: Annotationtracks
description: Set timer to update annotationtracks every friday at 20 (UTC time, summer=18, winter=19)
enabled: true

trigger:
  type: "core.st2.CronTimer"
  parameters:
      timezone: "UTC"
      day_of_week: "fri"
      hour: "18"
      minute: "0"
      second: "0"

action:
  ref: Annotationtracks.update_structuralvariant_tracks_gens
  parameters:
    hosts: "{{ config_context.hosts }}"
    cwd: "{{ config_context.cwd }}"







