name: informative_annotationtrack_timer
pack: annotationtracks
description: Set timer to update informative annotationtracks once a month
enabled: true

trigger:
  type: "core.st2.CronTimer"
  parameters:
      timezone: "UTC"
      month: "*"
      day: "1"
      hour: "0"
      minute: "0"
      second: "0"

action:
  ref: annotationtracks.update_informative_tracks_gens

    
